# Generated by Django 5.2.5 on 2026-04-18 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="新的皮肤问诊", max_length=120, verbose_name="会话标题"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(db_index=True, max_length=80, verbose_name="会话标识"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="上下文摘要"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosis_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能问诊会话",
                "verbose_name_plural": "智能问诊会话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "用户"), ("assistant", "AI助手")],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "references",
                    models.JSONField(blank=True, default=list, verbose_name="RAG参考"),
                ),
                (
                    "graph_paths",
                    models.JSONField(blank=True, default=list, verbose_name="知识图谱路径"),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="使用模型"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="app01.diagnosisconversation",
                        verbose_name="所属会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "智能问诊消息",
                "verbose_name_plural": "智能问诊消息",
                "ordering": ["created_at"],
            },
        ),
    ]
