# Generated by Django 5.2.5 on 2026-04-19 16:45

import app01.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_diagnosisconversation_diagnosismessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=160, verbose_name="文档标题")),
                ("file", models.FileField(upload_to=app01.models.knowledge_document_upload_to, verbose_name="原始文件")),
                ("file_type", models.CharField(default="txt", max_length=20, verbose_name="文件类型")),
                ("chunk_strategy", models.CharField(default="medical_recursive", max_length=80, verbose_name="切片策略")),
                ("status", models.CharField(default="ready", max_length=20, verbose_name="处理状态")),
                ("total_chars", models.PositiveIntegerField(default=0, verbose_name="总字符数")),
                ("total_chunks", models.PositiveIntegerField(default=0, verbose_name="切片数量")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "知识库文档",
                "verbose_name_plural": "知识库文档",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_index", models.PositiveIntegerField(verbose_name="分块序号")),
                ("page_label", models.CharField(blank=True, default="", max_length=40, verbose_name="页码标签")),
                ("content", models.TextField(verbose_name="切片内容")),
                ("token_estimate", models.PositiveIntegerField(default=0, verbose_name="估计 token 数")),
                ("start_offset", models.PositiveIntegerField(default=0, verbose_name="起始位置")),
                ("end_offset", models.PositiveIntegerField(default=0, verbose_name="结束位置")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="app01.knowledgedocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识切片",
                "verbose_name_plural": "知识切片",
                "ordering": ["document_id", "chunk_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="knowledgechunk",
            constraint=models.UniqueConstraint(fields=("document", "chunk_index"), name="unique_document_chunk_index"),
        ),
    ]
