# Generated by Django 5.2.5 on 2026-04-23 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_knowledgedocument_knowledgechunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosismessage",
            name="graph_payload",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="RAGGraph结构化结果"
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="实体名称")),
                (
                    "normalized_name",
                    models.CharField(
                        db_index=True, max_length=140, verbose_name="标准化名称"
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("disease", "疾病/主题"),
                            ("symptom", "症状"),
                            ("body_part", "部位"),
                            ("morphology", "皮损形态"),
                            ("trigger", "诱因"),
                            ("check", "检查"),
                            ("risk", "风险信号"),
                            ("care", "护理建议"),
                            ("evidence", "证据来源"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="实体类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="实体描述"),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="rag_graph",
                        max_length=80,
                        verbose_name="来源",
                    ),
                ),
                ("confidence", models.FloatField(default=0.8, verbose_name="实体置信度")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "医学图谱实体",
                "verbose_name_plural": "医学图谱实体",
                "ordering": ["entity_type", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("normalized_name", "entity_type"),
                        name="unique_knowledge_entity_type_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("HAS_SYMPTOM", "具有症状"),
                            ("LOCATED_AT", "发生部位"),
                            ("HAS_MORPHOLOGY", "皮损形态"),
                            ("TRIGGERED_BY", "相关诱因"),
                            ("NEEDS_CHECK", "建议检查"),
                            ("RISK_SIGNAL", "风险信号"),
                            ("SUGGESTS_CARE", "护理建议"),
                            ("EVIDENCED_BY", "证据来源"),
                            ("DIFFERENTIAL_WITH", "鉴别诊断"),
                        ],
                        db_index=True,
                        max_length=40,
                        verbose_name="关系类型",
                    ),
                ),
                ("weight", models.FloatField(default=1.0, verbose_name="关系权重")),
                (
                    "evidence_text",
                    models.TextField(blank=True, default="", verbose_name="证据文本"),
                ),
                (
                    "evidence_source",
                    models.CharField(
                        blank=True, default="", max_length=160, verbose_name="证据来源"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        default="structured",
                        max_length=40,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "page_label",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="页码标签"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_relations",
                        to="app01.knowledgeentity",
                        verbose_name="客体实体",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_relations",
                        to="app01.knowledgeentity",
                        verbose_name="主体实体",
                    ),
                ),
            ],
            options={
                "verbose_name": "医学图谱关系",
                "verbose_name_plural": "医学图谱关系",
                "ordering": ["-weight", "relation_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "subject",
                            "relation_type",
                            "object",
                            "evidence_source",
                        ),
                        name="unique_knowledge_relation_evidence",
                    )
                ],
            },
        ),
    ]
