"""
Django settings for DM-AI project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() in {"1", "true", "yes", "on"}


def env_int(name, default):
    try:
        return int(os.getenv(name, default))
    except (TypeError, ValueError):
        return default


def env_str(name, default=""):
    value = os.getenv(name)
    return value if value not in (None, "") else default

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_str(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-only-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_str("DJANGO_ALLOWED_HOSTS", "*").split(",")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01.apps.App01Config',
    'users.apps.UsersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DM-AI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': []
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app01.context_processors.external_ai_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'DM-AI.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DB_ENGINE = env_str("DB_ENGINE", "sqlite").lower()
if DB_ENGINE == "mysql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env_str("DB_NAME", "medical_db"),
            "USER": env_str("DB_USER", "root"),
            "PASSWORD": env_str("DB_PASSWORD", ""),
            "HOST": env_str("DB_HOST", "127.0.0.1"),
            "PORT": env_str("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
                "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / env_str("SQLITE_NAME", "db.sqlite3"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 讯飞星火的API
SPARK_CONFIG = {
    "APPID": os.getenv("SPARK_APPID", ""),
    "API_KEY": os.getenv("SPARK_API_KEY", ""),
    "API_SECRET": os.getenv("SPARK_API_SECRET", ""),
    "SPARK_URL": env_str("SPARK_URL", "wss://spark-api.xf-yun.com/v4.0/chat"),
    "DOMAIN": env_str("SPARK_DOMAIN", "4.0Ultra"),
}

# 缓存
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'diagnosis-cache',
    }
}


# 大模型API：兼容旧 DeepSeek 变量，并提供统一医疗问诊/影像解读配置
DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DASHSCOPE_API_KEY = os.getenv("DASHSCOPE_API_KEY")
BASE_URL = os.getenv("BASE_URL")
MEDICAL_LLM_API_KEY = os.getenv("MEDICAL_LLM_API_KEY") or DASHSCOPE_API_KEY or DEEPSEEK_API_KEY
MEDICAL_LLM_BASE_URL = os.getenv("MEDICAL_LLM_BASE_URL") or BASE_URL
MEDICAL_LLM_MODEL = env_str("MEDICAL_LLM_MODEL", "deepseek-chat")
MEDICAL_VISION_MODEL = env_str("MEDICAL_VISION_MODEL", MEDICAL_LLM_MODEL)
MEDICAL_VISION_SEND_IMAGE = env_bool("MEDICAL_VISION_SEND_IMAGE", False)
MEDICAL_LLM_TIMEOUT = env_int("MEDICAL_LLM_TIMEOUT", 60)
COZE_TOKEN = os.getenv("COZE_TOKEN", "")
COZE_BOT_ID = os.getenv("COZE_BOT_ID", "")

# 可选知识图谱后端。未配置时使用本地 MedicalKnowledge 构建轻量图谱证据。
NEO4J_URI = os.getenv("NEO4J_URI", "")
NEO4J_USER = os.getenv("NEO4J_USER", "")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "")

# 目标检测的API
OBJECT_DETECTION = {
    "API_KEY": os.getenv("OBJECT_DETECTION_API_KEY", ""),
    "URL": env_str("OBJECT_DETECTION_URL", "https://api.va.landing.ai/v1/tools/agentic-object-detection"),
}

# 自定义用户模型
DEFAULT_INFERENCE_DEVICE = env_str("INFERENCE_DEVICE", "auto").lower()
AI_INFERENCE = {
    "DEFAULT_DEVICE": DEFAULT_INFERENCE_DEVICE,
    "SKIN_DEVICE": env_str("SKIN_DEVICE", DEFAULT_INFERENCE_DEVICE).lower(),
    "YOLO_DEVICE": env_str("YOLO_DEVICE", DEFAULT_INFERENCE_DEVICE).lower(),
    "YOLO_HALF": env_bool("YOLO_HALF", False),
    "FSL_SKIN_PATH": env_str("FSL_SKIN_PATH", "D:/AI/FSL_skin"),
}

AUTH_USER_MODEL = 'users.UserProfile'

# 登录URL（用于 @login_required 装饰器）
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/index/'
LOGOUT_REDIRECT_URL = '/login/'

# Media文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 语言和时区设置
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
